### ISSUE TITLE
Update checkstyle.xml

### ISSUE THREAD

**Issue by llorllale** [llorllale/youtrack-api#164]
Use [this](https://github.com/llorllale/releasecat-maven-plugin/blob/master/checkstyle.xml) one.

**Comment by 0pdd** [comment]
@llorllale the puzzle [#168](https://github.com/llorllale/youtrack-api/issues/168) is still not solved.

**Comment by 0pdd** [comment]
@llorllale the puzzle [#171](https://github.com/llorllale/youtrack-api/issues/171) is still not solved; solved: [#168](https://github.com/llorllale/youtrack-api/issues/168).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#173](https://github.com/llorllale/youtrack-api/issues/173) is still not solved; solved: [#168](https://github.com/llorllale/youtrack-api/issues/168), [#171](https://github.com/llorllale/youtrack-api/issues/171).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#175](https://github.com/llorllale/youtrack-api/issues/175) is still not solved; solved: [#168](https://github.com/llorllale/youtrack-api/issues/168), [#171](https://github.com/llorllale/youtrack-api/issues/171), [#173](https://github.com/llorllale/youtrack-api/issues/173).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#177](https://github.com/llorllale/youtrack-api/issues/177) is still not solved; solved: [#168](https://github.com/llorllale/youtrack-api/issues/168), [#171](https://github.com/llorllale/youtrack-api/issues/171), [#173](https://github.com/llorllale/youtrack-api/issues/173), [#175](https://github.com/llorllale/youtrack-api/issues/175).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#179](https://github.com/llorllale/youtrack-api/issues/179) is still not solved; solved: [#168](https://github.com/llorllale/youtrack-api/issues/168), [#171](https://github.com/llorllale/youtrack-api/issues/171), [#173](https://github.com/llorllale/youtrack-api/issues/173), [#175](https://github.com/llorllale/youtrack-api/issues/175), [#177](https://github.com/llorllale/youtrack-api/issues/177).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#181](https://github.com/llorllale/youtrack-api/issues/181) is still not solved; solved: [#168](https://github.com/llorllale/youtrack-api/issues/168), [#171](https://github.com/llorllale/youtrack-api/issues/171), [#173](https://github.com/llorllale/youtrack-api/issues/173), [#175](https://github.com/llorllale/youtrack-api/issues/175), [#177](https://github.com/llorllale/youtrack-api/issues/177), [#179](https://github.com/llorllale/youtrack-api/issues/179).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#183](https://github.com/llorllale/youtrack-api/issues/183) is still not solved; solved: [#168](https://github.com/llorllale/youtrack-api/issues/168), [#171](https://github.com/llorllale/youtrack-api/issues/171), [#173](https://github.com/llorllale/youtrack-api/issues/173), [#175](https://github.com/llorllale/youtrack-api/issues/175), [#177](https://github.com/llorllale/youtrack-api/issues/177), [#179](https://github.com/llorllale/youtrack-api/issues/179), [#181](https://github.com/llorllale/youtrack-api/issues/181).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#186](https://github.com/llorllale/youtrack-api/issues/186) is still not solved; solved: [#168](https://github.com/llorllale/youtrack-api/issues/168), [#171](https://github.com/llorllale/youtrack-api/issues/171), [#173](https://github.com/llorllale/youtrack-api/issues/173), [#175](https://github.com/llorllale/youtrack-api/issues/175), [#177](https://github.com/llorllale/youtrack-api/issues/177), [#179](https://github.com/llorllale/youtrack-api/issues/179), [#181](https://github.com/llorllale/youtrack-api/issues/181), [#183](https://github.com/llorllale/youtrack-api/issues/183).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#188](https://github.com/llorllale/youtrack-api/issues/188) is still not solved; solved: [#168](https://github.com/llorllale/youtrack-api/issues/168), [#171](https://github.com/llorllale/youtrack-api/issues/171), [#173](https://github.com/llorllale/youtrack-api/issues/173), [#175](https://github.com/llorllale/youtrack-api/issues/175), [#177](https://github.com/llorllale/youtrack-api/issues/177), [#179](https://github.com/llorllale/youtrack-api/issues/179), [#181](https://github.com/llorllale/youtrack-api/issues/181), [#183](https://github.com/llorllale/youtrack-api/issues/183), [#186](https://github.com/llorllale/youtrack-api/issues/186).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#190](https://github.com/llorllale/youtrack-api/issues/190) is still not solved; solved: [#168](https://github.com/llorllale/youtrack-api/issues/168), [#171](https://github.com/llorllale/youtrack-api/issues/171), [#173](https://github.com/llorllale/youtrack-api/issues/173), [#175](https://github.com/llorllale/youtrack-api/issues/175), [#177](https://github.com/llorllale/youtrack-api/issues/177), [#179](https://github.com/llorllale/youtrack-api/issues/179), [#181](https://github.com/llorllale/youtrack-api/issues/181), [#183](https://github.com/llorllale/youtrack-api/issues/183), [#186](https://github.com/llorllale/youtrack-api/issues/186), [#188](https://github.com/llorllale/youtrack-api/issues/188).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#192](https://github.com/llorllale/youtrack-api/issues/192) is still not solved; solved: [#168](https://github.com/llorllale/youtrack-api/issues/168), [#171](https://github.com/llorllale/youtrack-api/issues/171), [#173](https://github.com/llorllale/youtrack-api/issues/173), [#175](https://github.com/llorllale/youtrack-api/issues/175), [#177](https://github.com/llorllale/youtrack-api/issues/177), [#179](https://github.com/llorllale/youtrack-api/issues/179), [#181](https://github.com/llorllale/youtrack-api/issues/181), [#183](https://github.com/llorllale/youtrack-api/issues/183), [#186](https://github.com/llorllale/youtrack-api/issues/186), [#188](https://github.com/llorllale/youtrack-api/issues/188), [#190](https://github.com/llorllale/youtrack-api/issues/190).

**Comment by 0pdd** [comment]
@llorllale all 12 puzzles are solved here: [#168](https://github.com/llorllale/youtrack-api/issues/168), [#171](https://github.com/llorllale/youtrack-api/issues/171), [#173](https://github.com/llorllale/youtrack-api/issues/173), [#175](https://github.com/llorllale/youtrack-api/issues/175), [#177](https://github.com/llorllale/youtrack-api/issues/177), [#179](https://github.com/llorllale/youtrack-api/issues/179), [#181](https://github.com/llorllale/youtrack-api/issues/181), [#183](https://github.com/llorllale/youtrack-api/issues/183), [#186](https://github.com/llorllale/youtrack-api/issues/186), [#188](https://github.com/llorllale/youtrack-api/issues/188), [#190](https://github.com/llorllale/youtrack-api/issues/190), [#192](https://github.com/llorllale/youtrack-api/issues/192).
