### ISSUE TITLE
Use llorllale/cactoos-matchers for tests

### ISSUE THREAD

**Issue by llorllale** [llorllale/youtrack-api#202]
Use [llorllale/cactoos-matchers](https://github.com/llorllale/cactoos-matchers) for tests where ever possible. Also, wherever possible, stop using static methods from `Matcher` and start using their object counterparts.

**Comment by 0pdd** [comment]
@llorllale the puzzle [#204](https://github.com/llorllale/youtrack-api/issues/204) is still not solved.

**Comment by 0pdd** [comment]
@llorllale the puzzle [#206](https://github.com/llorllale/youtrack-api/issues/206) is still not solved; solved: [#204](https://github.com/llorllale/youtrack-api/issues/204).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#219](https://github.com/llorllale/youtrack-api/issues/219) is still not solved; solved: [#204](https://github.com/llorllale/youtrack-api/issues/204), [#206](https://github.com/llorllale/youtrack-api/issues/206).
